//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamLab00004.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Card_ID { get; set; }
        public System.DateTime Card_Reg_Date { get; set; }
        public int Account_ID { get; set; }
        public int Card_Type_ID { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Card_Type Card_Type { get; set; }
    }
}
