//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamLab00004.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public int Account_ID { get; set; }
        public int Transaction_Type_ID { get; set; }
        public System.DateTime Transaction_Date_Time { get; set; }
        public double Transaction_Amount { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
